name: CI
on:
  push:
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    ################################################################################
    # Checkout
    ################################################################################
    - name: Checkout
      uses: actions/checkout@v4
    ################################################################################
    # Setup Rust
    ################################################################################
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    ################################################################################
    # Build
    ################################################################################
    - name: Debug Build
      run: cargo build
    - name: Release Build
      run: cargo build -r
